from typing import Literal
from pydantic import BaseModel


class Message(BaseModel):
    """
    A model representing a message in a chat.

    Attributes:
        role (Literal['system', 'assistant', 'user', 'function', 'tool', 'developer']):
            The role of the message sender. Supported values are:
            - 'system': Messages set by the system to provide instructions or context.
            - 'assistant': Responses generated by the assistant.
            - 'user': Input messages from the user.
            - 'function': Messages related to function calls.
            - 'tool': Messages related to tool interactions.
            - 'developer': Messages from the developer for debugging or special instructions.
        content (str): The content of the message.
    """

    role: Literal["system", "assistant", "user", "function", "tool", "developer"]
    content: str
